from pydantic import BaseModel, Field


class SearchQueries(BaseModel):
    """Structured output containing search queries generated by the research agent."""

    queries: list[str] = Field(
        ...,
        description="2-3 distinct, targeted search queries derived from the user's question",
    )
